name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:test:prepare

      - name: Build CSS
        run: |
          bundle exec rails tailwindcss:build

      - name: Precompile assets
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails assets:precompile

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test 